To build reliable predictions of Bitcoin transaction fees, effective data preprocessing into sensible inputs and appropriate model selections are critical. 

## Data Preprocessing
First and foremost, we select the *fastestFee* rate, recommended fee for fastest confirmation, under Fee Rates category in @tbl-description as the primary response variable, as it serves as a clear benchmark for users prioritizing transaction speed. Given the right-skewed nature of the fee distribution, we apply a logarithmic transformation to improve model performance. 

Several other challenges arise during this process. First, we detected outliers that may represent data entry errors or anomalies, such as BTC prices recorded as -1. Second, documentation from the data source is limited. Third, transaction behavior is expected to vary over time, with differences across weekdays and weekends, as well as possible seasonal patterns. Finally, relationships between variables like transaction volume and fee rates may hold important signals that require further exploration.

To address these issues, we intend to first correct outliers and abnormal values through imputation. We also inspect feature definitions and cross-validate them to understand how certain features are computed. We further analyze and visualize the time-series data for temporal patterns and signs of seasonality, subject to the period covered. Then, we compute pairwise correlations across different features (e.g. transaction volume and fee rates) and amongst similar features (e.g. median fee and total fees) to uncover meaningful relationships. Finally, we consider engineering time-based features—such as hour of day and day of week—as well as indicators of mempool congestion and major positive / negative events to enrich the feature space for downstream modeling. 
